name: snowflake-migration-demo

# Controls when the action will run.
on:
  push:
    branches:
      - main
    paths:
      - 'deploy/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest

    steps:

      # ---------------------------------------------------------
      # Step 1: Checkout the repository
      # ---------------------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v5


      # ---------------------------------------------------------
      # Step 2: Set up Python
      # ---------------------------------------------------------
      - name: Use Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'


      # ---------------------------------------------------------
      # Step 3: Install schemachange
      # ---------------------------------------------------------
      - name: Install schemachange
        run: |
          echo "Python version:"
          python --version

          echo "Installing schemachange..."
          python -m pip install --upgrade pip
          python -m pip install --upgrade schemachange

          echo "Schemachange version:"
          schemachange --version


      # ---------------------------------------------------------
      # Step 4: Verify Snowflake connection
      # ---------------------------------------------------------
      - name: Verify Snowflake connection
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SF_USERNAME }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
          SNOWFLAKE_ROLE: ${{ secrets.SF_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SF_DATABASE }}
        run: |
          echo "Testing Snowflake connection..."

          schemachange verify -L DEBUG


      # ---------------------------------------------------------
      # Step 5: Deploy Snowflake changes
      # ---------------------------------------------------------
      - name: Deploy Snowflake changes
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SF_USERNAME }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
          SNOWFLAKE_ROLE: ${{ secrets.SF_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SF_DATABASE }}
        run: |
          echo "Starting Snowflake deployment..."

          schemachange deploy \
            -f "$GITHUB_WORKSPACE/deploy" \
            -c "$SNOWFLAKE_DATABASE.SCHEMACHANGE.CHANGE_HISTORY" \
            --create-change-history-table \
            -L DEBUG

          echo "Snowflake deployment completed."
