name: snowflake-migration-demo

# Controls when the action will run.
on:
  push:
    branches:
      - main
    paths:
      - 'deploy/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v5

      # Set up Python
      - name: Use Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      # Install and run schemachange
      - name: Run schemachange
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SF_USERNAME }}
          SNOWFLAKE_ROLE: ${{ secrets.SF_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SF_DATABASE }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          python --version

          echo "Step 1: Installing schemachange"
          python -m pip install --upgrade pip
          python -m pip install --upgrade schemachange

          echo "Step 2: Running schemachange"
          schemachange deploy \
            -f "$GITHUB_WORKSPACE/deploy" \
            -c "$SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY" \
            --create-change-history-table
